<?php 
return [
    'permission' => array(
                    'users',
                    'roles',
                    'brands',
                    'product-category',
                    'products',
                    'product-addon',
                    'product-attribute',
                    'product-collection',                
                    'product-labels',
                    'tax',
                    'charges',
                    'coupon', 
                    'store-locator',
                    'service-center',
                    'banner',
                    'my-profile',
                    'homepage-setting-field',
                    'homepage-setting',
                    'warranty',
                    'customer',
                    'global',                   
                    'email-template',                    
                    'main_category',
                    'quick-link', 
                    'pincode',
                    'city',
                    'state',
                    'country',
                    'order-status',
                    'order',
                    'sms-template',
                    'payment-gateway', 
                    'reports',
                    'sub_category',                    
                    'wishlist',
                    'review',
                    'enquiry'                             

                ),
    
];